import React, { useEffect, useMemo, useRef, useState } from 'react';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000';
const WS_URL = import.meta.env.VITE_WS_URL || API.replace(/^http/, 'ws') + '/ws';
const getToken = () => localStorage.getItem('chat_token');
const saveAuth = (data) => { localStorage.setItem('chat_token', data.token); localStorage.setItem('chat_user', JSON.stringify(data.user)); };

function Auth({ onLogin }) {
  const [register, setRegister] = useState(false); const [form, setForm] = useState({ username: '', email: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(e) { e.preventDefault(); setError(''); setLoading(true); try { const r = await fetch(`${API}/api/auth/${register ? 'register' : 'login'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const d = await r.json(); if (!r.ok) throw new Error(d.message); saveAuth(d); onLogin(d.user); } catch (x) { setError(x.message) } finally { setLoading(false) } }
  return <div className="auth-page"><div className="auth-card"><div className="logo">◉ PulseChat</div><h1>{register ? 'Create account' : 'Welcome back'}</h1><p className="muted">Real-time conversations, rooms and private messaging.</p><form onSubmit={submit}>{register && <input placeholder="Username" minLength="3" value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} />}<input type="email" placeholder="Email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /><input type="password" placeholder="Password" required minLength="8" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} />{error && <div className="error">{error}</div>}<button disabled={loading}>{loading ? 'Please wait…' : register ? 'Sign up' : 'Log in'}</button></form><button className="link-btn" onClick={() => { setRegister(!register); setError('') }}>{register ? 'Already have an account? Log in' : 'New here? Create an account'}</button></div></div>
}

function App() { const [user, setUser] = useState(() => { try { return JSON.parse(localStorage.getItem('chat_user')) } catch { return null } }); return user ? <Chat user={user} onLogout={() => { localStorage.clear(); setUser(null) }} /> : <Auth onLogin={setUser} /> }

function Chat({ user, onLogout }) {
  const [rooms, setRooms] = useState([]), [users, setUsers] = useState([]), [active, setActive] = useState(null), [messages, setMessages] = useState([]), [text, setText] = useState(''), [typing, setTyping] = useState(''), [online, setOnline] = useState([]), [newRoom, setNewRoom] = useState(''), [search, setSearch] = useState('');
  const ws = useRef(null), bottom = useRef(null), typingTimer = useRef(null);
  const activeLabel = active?.kind === 'room' ? active.room.name : active?.user?.username;
  async function load() { const h = { Authorization: `Bearer ${getToken()}` }; const [r, u] = await Promise.all([fetch(`${API}/api/rooms`, { headers: h }), fetch(`${API}/api/rooms/users/all`, { headers: h })]); if (r.ok) setRooms((await r.json()).rooms); if (u.ok) setUsers((await u.json()).users) }
  useEffect(() => { load(); const socket = new WebSocket(`${WS_URL}?token=${encodeURIComponent(getToken())}`); ws.current = socket; socket.onmessage = e => { const d = JSON.parse(e.data); if (d.type === 'presence') setOnline(d.online); if (d.type === 'typing' && d.isTyping) { setTyping(`${d.username} is typing…`); clearTimeout(typingTimer.current); typingTimer.current = setTimeout(() => setTyping(''), 1500) } if (d.type === 'message' || d.type === 'private-message') setMessages(m => [...m, d.message]); if (d.type === 'notification') alert(d.message) }; socket.onclose = () => { }; return () => socket.close() }, []);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: 'smooth' }) }, [messages]);
  async function chooseRoom(room) { setActive({ kind: 'room', room }); setMessages([]); const r = await fetch(`${API}/api/messages/room/${room._id}`, { headers: { Authorization: `Bearer ${getToken()}` } }); if (r.ok) setMessages((await r.json()).messages); ws.current?.send(JSON.stringify({ type: 'join-room', roomId: room._id })) }
  async function chooseUser(u) { setActive({ kind: 'user', user: u }); setMessages([]); const r = await fetch(`${API}/api/messages/private/${u._id}`, { headers: { Authorization: `Bearer ${getToken()}` } }); if (r.ok) setMessages((await r.json()).messages) }
  async function createRoom(e) { e.preventDefault(); if (!newRoom.trim()) return; const r = await fetch(`${API}/api/rooms`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${getToken()}` }, body: JSON.stringify({ name: newRoom }) }); const d = await r.json(); if (r.ok) { setRooms([d.room, ...rooms]); setNewRoom('') } else alert(d.message) }
  function send() { if (!text.trim() || !active) return; ws.current?.send(JSON.stringify(active.kind === 'room' ? { type: 'room-message', text } : { type: 'private-message', recipientId: active.user._id, text })); setText(''); ws.current?.send(JSON.stringify({ type: 'typing', isTyping: false })) }
  function typingInput(e) { setText(e.target.value); if (active?.kind === 'room') ws.current?.send(JSON.stringify({ type: 'typing', isTyping: true })) }
  const filteredUsers = useMemo(() => users.filter(u => u.username.toLowerCase().includes(search.toLowerCase())), [users, search]);
  return <div className="app"><aside><div className="side-head"><div className="logo">◉ PulseChat</div><div className="me"><span className="avatar">{user.username[0].toUpperCase()}</span><span><b>{user.username}</b><small>Online</small></span></div></div><div className="side-scroll"><section><div className="section-title">ROOMS</div><form className="room-form" onSubmit={createRoom}><input value={newRoom} onChange={e => setNewRoom(e.target.value)} placeholder="New room…" /><button>+</button></form>{rooms.map(r => <button key={r._id} className={`nav-item ${active?.room?._id === r._id ? 'active' : ''}`} onClick={() => chooseRoom(r)}># {r.name}</button>)}</section><section><div className="section-title">DIRECT MESSAGES</div><input className="search" placeholder="Find a user…" value={search} onChange={e => setSearch(e.target.value)} />{filteredUsers.map(u => <button key={u._id} className={`nav-item ${active?.user?._id === u._id ? 'active' : ''}`} onClick={() => chooseUser(u)}><span className={`dot ${online.includes(u._id) ? 'on' : ''}`}></span>{u.username}</button>)}</section></div><button className="logout" onClick={async () => { try { await fetch(`${API}/api/auth/logout`, { method: 'POST', headers: { Authorization: `Bearer ${getToken()}` } }) } finally { onLogout() } }}>Log out</button></aside><main><header><div><h2>{activeLabel || 'Select a conversation'}</h2><span className="muted">{active?.kind === 'room' ? 'Room chat' : active?.user ? (online.includes(active.user._id) ? '● Online' : '○ Offline') : ''}</span></div><span className="connection"><i></i> Live</span></header><div className="messages">{!active ? <div className="empty"><div className="empty-icon">💬</div><h2>Start chatting</h2><p>Choose a room or a person to send an instant message.</p></div> : messages.map((m, i) => <div className={`msg ${m.sender?._id === user.id ? 'mine' : ''}`} key={m._id || i}><div className="msg-avatar">{(m.sender?.username || '?')[0].toUpperCase()}</div><div><div className="meta"><b>{m.sender?.username || 'You'}</b><span>{new Date(m.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></div><div className="bubble">{m.text}</div></div></div>)}<div ref={bottom} /></div>{active && <><div className="typing">{typing}</div><div className="composer"><input value={text} onChange={typingInput} onKeyDown={e => e.key === 'Enter' && !e.shiftKey && (e.preventDefault(), send())} placeholder={`Message ${active.kind === 'room' ? '#' + active.room.name : '@' + active.user.username}`} /><button onClick={send}>Send ↗</button></div></>}</main></div>
}
export default App;
